#!/usr/bin/env python
# Copyright 2015 Blue Box Cloud, an IBM Company
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import argparse
import subprocess
import sys


def generate_profile(csvfile, imagefile, title):
    proc = subprocess.Popen(
        ["./profile.R",
         "datafile='%s'" % csvfile,
         "imagefile='%s'" % imagefile,
         "title='%s'" % title],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        sys.exit("Profile generation failed!\nOUTPUT:\n%s" % stderr)

    print "Wrote: %s" % imagefile


def main():
    args = argparse.ArgumentParser()
    args.add_argument("--image-file", dest="imagefile", default="profile.png")
    args.add_argument("--title", default="Ansible Playbook Performance Profile")
    args.add_argument("csvfile")
    args = args.parse_args()
    generate_profile(args.csvfile, args.imagefile, args.title)


if __name__ == "__main__":
    main()
